#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;

require 'vendor/autoload.php';

$app = new Application('Laracast Demo', '1.0'); 

//register new command
//make sure command is executable
    //run this in terminal chmod +x filename
    
$app->register('sayHelloTo')
    ->setDescription('Greeting a person')
    ->addArgument('name',InputArgument::OPTIONAL, 'Your Name')
    ->setCode(function(InputInterface $input, OutputInterface $output)
    {
        $name = $input->getArgument('name');
        $output->writeln("Hello World This Is $name");
    });

//start up the application    
$app->run();    